# Python Game Client Side 2021 - by A.G.
# Python Exercise in "Socket", GUI with "Tkinter";
# Game to Guess the random number generated by server.

from tkinter import *
import socket

main_win = Tk()
main_win.geometry("640x480")
#main_win.resizable(0, 0)
main_win.title("Guess Number")

def score_board():

    main_win.iconify()
    f = open("scoreBoard.txt", "r")
    scoreList = f.read()
    f.close()
    score_window = Toplevel(main_win)
    score_window.title("Score")
    score_window.geometry("480*640")
    score_window.resizable(0, 0)
    canvas_score = Canvas(score_window, width=480, height=640)
    canvas_score.pack(fill="both",expand=True)
    canvas_score.create_image(0, 0, image=bg_score, anchor="nw")

def hover_in(e):                                                          # Cursor over button effect / in
    e.widget["background"] = "#FA9F42"


def hover_out(e):                                                         # Cursor over button effect / out
    e.widget["background"] = "#721817"


def login():
    main_win.iconify()




bg_main = PhotoImage(file="img/bg-math.png")
bg_score = PhotoImage(file="img/score.png")
bg_login = PhotoImage(file="img/login.png")
bg_game = PhotoImage(file="img/game.png")

canvas_main = Canvas(main_win, width=640, height=480)
canvas_main.pack(fill="both", expand=True)
canvas_main.create_image(0,0, image=bg_main,anchor="nw")

canvas_main.create_text(360, 60, text="Guess the Number", fill="#FA9F42",
                        font="Times 38 bold",justify="center",anchor="n")
b_new_game = Button(canvas_main, text="N E W   G A M E", height=2, width=26, bg="#721817", relief="raised",  # New Game
                    activebackground="#721817", command=login, state=NORMAL, font="Times 16 ")
b_score = Button(canvas_main, text="S C O R E", height=2, width=26, bg="#721817", relief="raised",           # Score
                 activebackground="#721817", command=score_board, state=NORMAL, font="Times 16")
b_exit = Button(canvas_main, text="E X i T", height=2, width=26, bg="#721817", relief="raised",              # Exit
                activebackground="#721817", command=main_win.destroy, state=NORMAL, font="Times 16")
b_new_game.place(x=320, y=220, anchor="center")     # Button place
b_new_game.bind("<Enter>", hover_in)                # Hover in / out
b_new_game.bind("<Leave>", hover_out)

b_score.place(x=320, y=290, anchor="center")        # Button place
b_score.bind("<Enter>", hover_in)                   # Hover in / out
b_score.bind("<Leave>", hover_out)

b_exit.place(x=320, y=380, anchor="center")         # Button place
b_exit.bind("<Enter>", hover_in)                    # Hover in / out
b_exit.bind("<Leave>", hover_out)

main_win.mainloop()



